### ISSUE TITLE
Scoping - uikit roadmap

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/uikit#11]
- Events should be consistent
- Components should expose events and not just values
- Standardize events
- Consider upgrade plan for new projects. 
  - Consider breaking changes and adoption for all the projects we support now. 
  - Let's try to maintain backward compatibility!

Result: Take stock of where we are and where we would like to go. Wiki will be the result, with a breakdown of tasks.

**Comment by ciaranschutte** [comment]
https://wiki.oicr.on.ca/pages/viewpage.action?spaceKey=icgcargotech&title=UIKit+2.0
and tickets made in https://github.com/icgc-argo/uikit/issues
