### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/uikit#15]
- JEST and test setup needs to happen
- write unit tests for ~45 components
- write integration tests (form, form elements)
  - cover components that interact 
  - parent / child component interactions

**Comment by ciaranschutte** [comment]
framework/build all set up - only tests to write

**Comment by b-f-chan** [comment]
Need to list and break this out into smaller tasks

**Comment by b-f-chan** [comment]
@ciaranschutte - Suggest, write a few model tests that other developers and replicate and use as boilerplate later (e.g. choose 2 or 3)

**Comment by ciaranschutte** [comment]
https://testing-library.com/docs/react-testing-library/intro/

**Comment by b-f-chan** [comment]
done and tested but in feature branch in UIKit --> So this will depend on our UIkit release strategy
