### ISSUE TITLE
Design: Consistent event handling

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/uikit#18]
Components are handling events in various ways

## Detailed Description
* Multiselect component doesn't expose every event
* Click/focus/etc not exposed on all components
* **Want components to behave as if they were native**
* Will need to create events for some components since they are "molecules" instead of "atomic"

## Output
- Identify components we want to tackle first and what ht event interfaces will look like. Document in a wiki.

**Comment by samrichca** [comment]
some uikit components (like multiselect) have internal events that aren't exposed to outside/parent components, i.e. to update the internal state of that uikit component.

I'd like to expose all events so we can detect them and act upon in them in the rest of the page.

**Comment by ciaranschutte** [comment]
nb. breaking change

**Comment by ciaranschutte** [comment]
how do other libs handle this? eg. https://mui.com/

**Comment by ciaranschutte** [comment]
https://wiki.oicr.on.ca/display/icgcargotech/Events
