### ISSUE TITLE
Apply minimal set of changes from V2 branch

### ISSUE THREAD

**Issue by ciaranschutte** [icgc-argo/uikit#62]
uikit changes in v2 branch were headed towards making uikit entirely reusable across projects.
this is incorrect. we want to keep it ARGO specific.

there are still some changes which are applicable.

- local dev of uikit so projects can contribute as needed
  - building exports as a singular index.js
  - ensuring all exports are named or they don't work 
  - ensuring no collisions of named exports
- removing/updating some libraries (outdated or many versions behind)
- ensure peer dependencies of react and emotion work correctly
  - ensure requirements of using lib are well defined eg. is there a specific emotion version needed?

consuming projects will need to update. breaking changes because the import structure of components will be completely different.

**Comment by Buwujiu** [comment]
Will not release until we test UI kit integration with platform ui. Will leave ticket in Dev column.

**Comment by ciaranschutte** [comment]
@samrichca can this ticket be closed?
All the work you did has been pushed through to release right?

**Comment by samrichca** [comment]
@ciaranschutte it can be closed, integration with platform-UI is completed & available on QA.

For posterity: changes might be needed for support with DACO & other client projects.
